-- This migration is a duplicate of 20260612184311_society.
-- All tables and types were already created in that migration.
-- This file is intentionally left as a no-op to preserve migration history.
